### ISSUE TITLE
Informação do código do boleto

### ISSUE THREAD

**Issue by matheussilvasantos** [mundipagg/MundiAPI-RUBY#8]
Não há informação na resposta, após criar um `order`, sobre o código do boleto.

**Comment by matheussilvasantos** [comment]
@mmarini17 consegue dar uma olhada nisso?

**Comment by mmarini17** [comment]
Boa tarde @matheussilvasantos beleza cara ?

Vou dar uma olhada nesse problema e te dou uma resposta... beleza ?

**Comment by matheussilvasantos** [comment]
@mmarini17 beleza, fiz uma _pull request_ no repositório de vocês que soluciona o problema, se conseguir fazer o _merge_ já resolve para mim.

**Comment by mmarini17** [comment]
@matheussilvasantos Repositório atualizado.... verificamos que faltavam mais alguns campos também...

Qualquer coisa entre em contato brother ... 

Grande abraço

**Comment by matheussilvasantos** [comment]
@mmarini17 valeu :smile:
